# @package __global__

# environmental sounds dataset compiling all datasets
# with applied filters on tags
datasource:
  max_sample_rate: 16000
  max_channels: 1

  train: egs/train
  valid: egs/validation
  evaluate: egs/test
  generate: egs/test # identical to evaluate
